default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: postgres
  password: root1234
  port: 5432

development:
  <<: *default
  host: localhost
  database: BookManagementSystem_development
